CREATE TABLE `users` (                                                                                                                                                                                                                                                                                                                                                                                                                                               
          `userID` INT(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                          
          `username` VARCHAR(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                   
          `email` VARCHAR(255) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                     
          `password` VARCHAR(255) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                  
          `avatar` VARCHAR(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                
          `role` ENUM('user','admin') NOT NULL DEFAULT 'user',                                                                                                                                                                                                                                                                                                                                                                                                               
          `reset_token` VARCHAR(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                           
          `reset_expires` DATETIME DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                             
          PRIMARY KEY (`userID`)                                                                                                                                                                                                                                                                                                                                                                                                                                             
        ) ENGINE=INNODB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
        
CREATE TABLE `modules` (                                                                                                                                                                                                                                                                       
           `moduleID` INT(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                  
           `modulename` VARCHAR(255) NOT NULL,                                                                                                                                                                                                                                                          
           `modulecode` VARCHAR(20) NOT NULL,                                                                                                                                                                                                                                                           
           `subject` VARCHAR(50) NOT NULL,                                                                                                                                                                                                                                                              
           PRIMARY KEY (`moduleID`)                                                                                                                                                                                                                                                                     
         ) ENGINE=INNODB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci  

CREATE TABLE `posts` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
          `postID` INT(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
          `userID` INT(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
          `title` VARCHAR(255) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
          `moduleID` INT(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          `content` TEXT NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
          `image` VARCHAR(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
          `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
          PRIMARY KEY (`postID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
          KEY `moduleID` (`moduleID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          KEY `fk_posts_user` (`userID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
          CONSTRAINT `fk_posts_user` FOREIGN KEY (`userID`) REFERENCES `users` (`userID`) ON DELETE NO ACTION,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
          CONSTRAINT `posts_ibfk_2` FOREIGN KEY (`moduleID`) REFERENCES `modules` (`moduleID`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
        ) ENGINE=INNODB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci 
        
CREATE TABLE `replies` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
           `replyID` INT(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
           `postID` INT(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
           `userID` INT(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
           `content` TEXT NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
           `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
           PRIMARY KEY (`replyID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
           KEY `postID` (`postID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
           KEY `fk_reply_user` (`userID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
           CONSTRAINT `replies_ibfk_1` FOREIGN KEY (`userID`) REFERENCES `users` (`userID`) ON DELETE CASCADE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
           CONSTRAINT `replies_ibfk_2` FOREIGN KEY (`postID`) REFERENCES `posts` (`postID`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
         ) ENGINE=INNODB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
         
CREATE TABLE `contacts` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
	`contactID` INT(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        `userID` INT(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        `sender_email` VARCHAR(255) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        `message` TEXT NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        `image` VARCHAR(255) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        `sent_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
        `reply_message` TEXT DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        `reply_date` DATETIME DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        PRIMARY KEY (`contactID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        KEY `userID` (`userID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        CONSTRAINT `contacts_ibfk_1` FOREIGN KEY (`userID`) REFERENCES `users` (`userID`) ON DELETE CASCADE)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
	ENGINE=INNODB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci     

CREATE TABLE `likes` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
          `likeID` INT(11) NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
          `userID` INT(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
          `postID` INT(11) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
          PRIMARY KEY (`likeID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
          UNIQUE KEY `unique_user_post_like` (`userID`,`postID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
          UNIQUE KEY `UQ_user_post_like` (`userID`,`postID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
          KEY `fk_likes_post` (`postID`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
          CONSTRAINT `fk_likes_post` FOREIGN KEY (`postID`) REFERENCES `posts` (`postID`) ON DELETE CASCADE,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
          CONSTRAINT `fk_likes_user` FOREIGN KEY (`userID`) REFERENCES `users` (`userID`) ON DELETE CASCADE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci  